# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swiss_knife}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-10-11}
  s.description = %q{Several helpers for Rails 3}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "README.rdoc",
     "Rakefile",
     "lib/swiss_knife.rb",
     "lib/swiss_knife/action_controller.rb",
     "lib/swiss_knife/assets.rb",
     "lib/swiss_knife/dispatcher_js.rb",
     "lib/swiss_knife/helpers.rb",
     "lib/swiss_knife/i18n_js.rb",
     "lib/swiss_knife/jquery.rb",
     "lib/swiss_knife/jquery_ujs.rb",
     "lib/swiss_knife/jsmin.rb",
     "lib/swiss_knife/modernizr.rb",
     "lib/swiss_knife/railtie.rb",
     "lib/swiss_knife/rake_tasks.rb",
     "lib/swiss_knife/rspec.rb",
     "lib/swiss_knife/rspec/have_tag.rb",
     "lib/swiss_knife/support/remote_file.rb",
     "lib/swiss_knife/version.rb",
     "spec/controllers/application_controller_spec.rb",
     "spec/helpers/helpers_spec.rb",
     "spec/resources/assets.yml",
     "spec/resources/assets/javascripts/application.js",
     "spec/resources/assets/javascripts/jquery.js",
     "spec/resources/assets/javascripts/rails.js",
     "spec/resources/assets/stylesheets/main.css",
     "spec/resources/assets/stylesheets/reset.css",
     "spec/resources/assets/stylesheets/shared.css",
     "spec/resources/stylesheets/_shared.less",
     "spec/resources/stylesheets/main.less",
     "spec/resources/stylesheets/reset.css",
     "spec/resources/stylesheets/ui/tab.css",
     "spec/resources/stylesheets/ui/window.less",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/config/boot.rb",
     "spec/support/config/locales/en.yml",
     "spec/support/log/test.log",
     "spec/support/rspec/remote_file_shared.rb",
     "spec/swiss_knife/assets_spec.rb",
     "spec/swiss_knife/dispatcher_js_spec.rb",
     "spec/swiss_knife/i18n_js_spec.rb",
     "spec/swiss_knife/jquery_spec.rb",
     "spec/swiss_knife/jquery_ujs_spec.rb",
     "spec/swiss_knife/modernizr_spec.rb"
  ]
  s.homepage = %q{http://github.com/fnando/swiss_knife}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Several helpers for Rails 3}
  s.test_files = [
    "spec/controllers/application_controller_spec.rb",
     "spec/helpers/helpers_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/config/boot.rb",
     "spec/support/rspec/remote_file_shared.rb",
     "spec/swiss_knife/assets_spec.rb",
     "spec/swiss_knife/dispatcher_js_spec.rb",
     "spec/swiss_knife/i18n_js_spec.rb",
     "spec/swiss_knife/jquery_spec.rb",
     "spec/swiss_knife/jquery_ujs_spec.rb",
     "spec/swiss_knife/modernizr_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

